{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dwbs.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dwbs.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host | quote }}
{{- with $.Values.ingress.tls.secret }}
      secretName: {{ $ | quote }}
{{- end }}
{{- end }}
  rules:
    - host: {{ $.Values.ingress.host | quote }}
      http:
        paths:
{{- range $name, $config := .Values.dwbs }}
{{- if $config.path }}
          - path: "/{{ $config.path }}"
            backend:
              serviceName: "{{ $fullName }}-{{ $name }}"
              servicePort: {{ $svcPort }}
{{- end }}
{{- end }}
{{- range $name, $config := .Values.statefulset }}
{{- if $config.path }}
          - path: "/{{ $config.path }}"
            backend:
              serviceName: "{{ $fullName }}-{{ $name }}"
              servicePort: {{ $svcPort }}
{{- end }}
{{- end }}
{{- end }}