{{- range $name, $config := .Values.statefulset }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "dwbs.fullname" $ }}-{{ $name }}"
  labels:
    app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name  }}"
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name  }}"
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
{{- end }}
