{{- range $name, $config := .Values.dwbs }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "dwbs.fullname" $ }}-{{ $name }}"
  labels:
    app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name }}"
    {{- include "dwbs.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name }}"
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
{{- end }}
