{{- range $name, $config := .Values.statefulset }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "dwbs.fullname" $ }}-{{ $name }}"
  labels:
    app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name  }}"
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name }}"
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  serviceName: "{{ include "dwbs.fullname" $ }}-{{ $name }}-headless"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "dwbs.name" $ }}-{{ $name }}"
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum | quote }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dwbs.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: "{{ $name }}"
        image: "{{ $.Values.registry.host }}/{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $config.image.pullPolicy | quote }}
{{- if $config.envFrom }}
        envFrom:
{{ toYaml $config.envFrom | indent 8 }}
{{- end }}
{{- if $config.ports }}
        ports:
{{ toYaml $config.ports | indent 8 }}
{{- end }}
{{- if $config.resources }}
        resources:
{{ toYaml $config.resources | indent 10 }}
{{- end }}
{{- if $config.livenessProbe }}
        livenessProbe:
{{ toYaml $config.livenessProbe | indent 10 }}
{{- end }}
{{- if $config.readinessProbe }}
        readinessProbe:
{{ toYaml $config.readinessProbe | indent 10 }}
{{- end }}
{{- if $config.volumeMounts }}
        volumeMounts:
{{ toYaml $config.volumeMounts | indent 10 }}
{{- end }}
{{- if $config.volumes }}
      volumes:
{{ toYaml $config.volumes | indent 8 }}
{{- end }}
{{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
{{- end }}
{{- if $.Values.affinity }}
      affinity:
{{ toYaml $.Values.affinity | indent 8 }}
{{- end }}
{{- if $.Values.tolerations }}
      tolerations:
{{ toYaml $.Values.tolerations | indent 8 }}
{{- end }}
{{- if and ( $config.volumeMounts ) (eq $.Values.persistence.enabled true) }}
  volumeClaimTemplates:
  - metadata:
      name: "pvc-{{ $name }}"
    spec:
      accessModes: [{{ $.Values.persistence.accessMode | quote }}]
      {{- if $.Values.persistence.storageClass }}
      {{- if (eq "-" $.Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ $.Values.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ $.Values.persistence.pvcSize | quote }}
{{- end }}
{{- end }}